name: RHEL 9 CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Change to self-hosted if using your RHEL machine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies (RHEL 9)
        run: |
          sudo dnf install -y gcc make python3 python3-pip

      - name: Verify Python Version
        run: python3 --version

      - name: Run a Simple Python Test
        run: python3 -c "print('Hello from RHEL 9 CI!')"

